name: Go
on: [push]
jobs:

  build:
    name: Build
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Get current time
      uses: gerred/actions/current-time@master
      id: current-time

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: echo git hash
      run: echo "${{ github.sha }} \n\r ${{ steps.current-time.outputs.time }}" > Release.txt
    - name: Build Golang Executorable Release
      run: go build -ldflags "-s -w -X main.buildTime=${{ steps.current-time.outputs.time }} -X main.gitHash=${{ github.sha }}" -o sshfortress_${{ matrix.platform }}.release
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          sshfortress_${{ matrix.platform }}.release
          Release.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
